### ISSUE TITLE
Air-sea flux fields cannot be computed in CMEPS

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/CMEPS#10]
When CMEPS is used in DATM-MOM6-CICE5, air-sea flux calculations cannot be done in the mediator.

CMEPS version used: f52f263.

Related issue: https://github.com/NOAA-EMC/DATM-MOM6-CICE5/issues/48

**Comment by DeniseWorthen** [comment]
This is primarily an issue with a missing MED med_phases_aofluxes_run in the runsequence. 

A second issue is that lwnet is not being sent to the ocean. 

Issue #12 has been created for fixing the FieldsExchange and prep_ocn phases to allow functioning for any nems mode (orig, frac and orig_data).
