### ISSUE TITLE
crash when running GFS PBL/sfclay and clm lake in RRFS ensemble

### ISSUE THREAD

**Issue by JiliDong-NOAA** [NOAA-EMC/CMEPS#104]
A couple of RRFS ensemble members crashed with GFS PBL (TKE-EDMF)/sfclay and clm lake combined. This happened when lake water was frozen to lake ice in clm lake.

The reason for the crash is because clm lake is called between surface layer scheme and PBL scheme. If there is a state change in clm lake, particularly water turning into ice, stability related variables over ice will be missing and cause the crash.

**Comment by DeniseWorthen** [comment]
@JiliDong-NOAA Can I close this issue?
