### ISSUE TITLE
ensure restart-at-end functionality is working in CMEPS 

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/CMEPS#118]
A configuration variable ``write_restart_at_endofrun`` is available in CMEPS. We need to test whether it is working and if not, find a solution. This may also involve the MOM6 and CICE6 Caps, which trigger restart-writing off the same configuration variables  used by CMEPS (``restart_n`` and ``restart_option``). Those components also need to have the same capability to write a restart at the end of the run.

**Comment by aerorahul** [comment]
I tested this as part of https://github.com/NOAA-EMC/global-workflow/pull/2510 and found that the restarts at the end of the forecast were present.  I used [this](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/ufs.configure.s2s_esmf.IN) template and did not have to add any variable.
