### ISSUE TITLE
CCPP-physics dependency has been removed

### ISSUE THREAD

**Issue by dustinswales** [NOAA-EMC/CMEPS#74]
A dependency listed in ufs/ccpp/data/MED_typedefs.meta, [physparam.f](https://github.com/NOAA-EMC/CMEPS/blob/f9f7541a4a7e7fd6009a3029c883bbbb289d6ef4/ufs/ccpp/data/MED_typedefs.meta#L1237), has (PR pending) been removed. It doesn't appear that physparam is used in MED_typedefs.F90, but with physparam.f in the meta file the ccpp_prebuild step is now failing for the [cpld_control_noaero_p8_agrid](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt.conf#L33)

**Comment by DeniseWorthen** [comment]
Change was committed with PR #72
